### PR TITLE
Add audio limiter

### PR DESCRIPTION
**Pull request by bibendovsky**

### CODE REVIEW

**Comment by bibendovsky** [comment]
Added audio limiter for default sound subsystem.
It limits final mix by a current volume.

Cvars:
- `s_limiter <0|1>`  
   Argument: 0 - disable, 1 - enable.  
   Changes applies immediately.

Test build:
[idt4-windows-i386-4ccd64c609aa55f9bab5e05acde36e69ed7eab90.zip](https://github.com/bibendovsky/idt4/files/9397283/idt4-windows-i386-4ccd64c609aa55f9bab5e05acde36e69ed7eab90.zip)

**Comment by Kappa971** [comment]
> Added audio limiter for default sound subsystem. It limits final mix by a current volume.
> 
> Cvars:
> 
>     * `s_limiter <0|1>`
>       Argument: 0 - disable, 1 - enable.
>       Changes applies immediately.
> 
> 
> Test build: [idt4-windows-i386-4ccd64c609aa55f9bab5e05acde36e69ed7eab90.zip](https://github.com/bibendovsky/idt4/files/9397283/idt4-windows-i386-4ccd64c609aa55f9bab5e05acde36e69ed7eab90.zip)

With this build the clipping distortion is less than in the vanilla Doom 3, but it is still very audible.
If I could turn down the game volume below -7db (probably at least -17/-20db for this game), the problem would be "solved", but as already mentioned, below that threshold the weapons become loud.

EDIT
Maybe I misunderstood...  For "default sound subsystem", do you mean EAX disabled? 
My testing was done with EAX enabled, but would the limiter be able to work in this case? Reverb and other audio effects are processed directly by the sound card, and these processing would probably increase the volume of samples that would otherwise have correct volume... But I could be wrong, I'm not an expert.

EDIT2
Also I have read that clipping can irreparably damage the speakers, so far I think I have not done any damage but Doom 3 scares me because it suffers a LOT of clipping, I would like to avoid doing further tests in this regard. It would be enough for me to be able to lower the game volume below -7db. If this can't be fixed, I will continue to use the combination -7db in game + sound card equalizer.

**Comment by bibendovsky** [comment]
> Maybe I misunderstood... For "default sound subsystem", do you mean EAX disabled?

Yes, it's a test for non-EAX/OpenAL sound subsystem.

**Comment by Kappa971** [comment]
> Yes, it's a test for non-EAX/OpenAL sound subsystem.

I don't notice any clipping in vanilla Doom 3 with EAX disabled.
In any case, I tried your source port with EAX disabled: I set the game volume to max (the Windows master volume is always set to 100%, on the web there are conflicting opinions about it so I don't know if it is correct to keep it like this ) and s_limiter "0" and behaves like vanilla Doom 3; with s_limiter "1", the limiter is actually doing something, I recorded these two videos:

https://user-images.githubusercontent.com/62349018/186140286-51ff0b73-5572-424f-9ca9-57e68359894a.mp4

https://user-images.githubusercontent.com/62349018/186140324-17558d37-1146-4b1b-9026-a839dad5e01f.mp4

I think it is impossible for the human ear to notice the clipping in the first video, I don't notice any distortion but for the limiter the volume of the shot against the metal wall is too loud. In other cases it seems to sound the same with s_limiter "0" or s_limiter "1", but I haven't done a thorough test.

**Comment by bibendovsky** [comment]
Shotgun shots against the metal wall.
System volume: 100%
Game volume (`s_volume`): 1st shot - `0 dB`, 2nd shot - `-6 dB`, 3rd shot - `-12 dB`.
The scale on the right is integer amplitude `[-32768 .. +32767]`.
Recorded with Xbox Game Bar.

doom3_s_limiter_0_db_0_m6_m12_202208231731
`s_limiter 0`

doom3_s_limiter_1_db_0_m6_m12_202208231731
`s_limiter 1`

**Comment by Kappa971** [comment]
> doom3_s_limiter_0_db_0_m6_m12_202208231731 `s_limiter 0`

I'm not an audio expert, but isn't this strange? Is it normal that it works like this without the limiter?

**Comment by bibendovsky** [comment]
> I'm not an audio expert, but isn't this strange? Is it normal that it works like this without the limiter?

Probably not.
IMO When user lowers the game volume it expects the overall volume of all active sounds don't go louder.

**Comment by Kappa971** [comment]
> Probably not. IMO When user lowers the game volume it expects the overall volume of all active sounds don't go louder.

The limiter is useful (not for EAX because I think it can't control the processing applied by the sound card), but I think there is something in Doom 3's internal mixer that is not working well.

**Comment by bibendovsky** [comment]
> The limiter is useful (not for EAX because I think it can't control the processing applied by the sound card), but I think there is something in Doom 3's internal mixer that is not working well.

Engine's mixer applies the game volume only for sounds, not for the final mix.

Unfortunately OpenAL API does not provide the mechanism to alter samples in the final mix.
The only way I see for now is to dynamically adjust the listener's volume.

**Comment by Kappa971** [comment]
> Engine's mixer applies the game volume only for sounds, not for the final mix.
> 
> Unfortunately OpenAL API does not provide the mechanism to alter samples in the final mix. The only way I see for now is to dynamically adjust the listener's volume.

But have you noticed that by decreasing the volume below -7db, the volume of the weapons (especially the machine gun) doesn't seem to decrease anymore (or much less than it should)? Or am I crazy? 😅

**Comment by bibendovsky** [comment]
> But have you noticed that by decreasing the volume below -7db, the volume of the weapons (especially the machine gun) doesn't seem to decrease anymore (or much less than it should)? Or am I crazy? 😅

Without the limiter?

**Comment by Kappa971** [comment]
> Without the limiter?

It happens with EAX disabled and `s_limiter "0"`, and EAX enabled with both `s_limiter "0"` and `s_limiter "1"`. 
With EAX disabled and `s_limiter "1"` it works as it should.

No other game I have tried has problems scaling the sounds according to the volume set in the menu, not even Prey which uses the same engine.

**Comment by bibendovsky** [comment]
> It happens with EAX disabled and `s_limiter "0"`, and EAX enabled with both `s_limiter "0"` and `s_limiter "1"`.

Set `s_volume` to `-14 dB` or lower.
Machine gun "fire" sounds have additional volume correction `+14 dB`.
See file `sound/weapons.sndshd` in `base/pak005.pk3`.
Lookup for "player_machinegun_fire" string.



> No other game I have tried has problems scaling the sounds according to the volume set in the menu, not even Prey which uses the same engine.

"Prey" developers had full source code of the engine. They could fix that.

**Comment by Kappa971** [comment]
> Set `s_volume` to `-14 dB` or lower. Machine gun "fire" sounds have additional volume correction `+14 dB`. See file `sound/weapons.sndshd` in `base/pak005.pk3`. Lookup for "player_machinegun_fire" string.
 
```
player_machinegun_fire {
	minDistance	5
	maxDistance	30
	volume	14

	sound/dane/Machine_Gun_Shot_V2/MACHGUN_SHOT_1v2.wav
	sound/dane/Machine_Gun_Shot_V2/MACHGUN_SHOT_2v2.wav
	sound/dane/Machine_Gun_Shot_V2/MACHGUN_SHOT_3v2.wav
	sound/dane/Machine_Gun_Shot_V2/MACHGUN_SHOT_4v2.wav
	sound/dane/Machine_Gun_Shot_V2/MACHGUN_SHOT_5v2.wav
	
}
```
```
player_shotgun_fire {
	minDistance	10
	maxDistance	30
	volume		9
	no_dups

	sound/weapons/shotgun/wetfire.wav
	sound/weapons/shotgun/wetfire3.wav
	sound/weapons/shotgun/wetfire5.wav

	//sound/weapons/shotgun/wetfire2.wav
	//sound/weapons/shotgun/wetfire4.wav
	

	//sound/weapons/shotgun/xfire_01.wav
	//sound/weapons/shotgun/xfire_02.wav
	//sound/weapons/shotgun/xfire_03.wav
	//sound/weapons/shotgun/xfire_04.wav
}
```
It's absurd to me, why do this? In practice, with `s_volume_dB "0"` no gain is applied but lowering `s_volume_dB`, the gain specified in that file will be applied?? +14db, +9db, it seems like a lot to me...

**Comment by bibendovsky** [comment]
> It's absurd to me, why do this? In practice, with `s_volume_dB "0"` no gain is applied but lowering `s_volume_dB`, the gain specified in that file will be applied?? +14db, +9db, it seems like a lot to me...

May be to make sure they are always audible if many of other sounds are playing at once.

**Comment by Kappa971** [comment]
> May be to make sure they are always audible if many of other sounds are playing at once.

It may be, but it doesn't work well. 
With s_volume_dB "0" (up to s_volume_dB "-7") weapons have a normal volume, not too strong and not too weak and I'm able to listen to audio logs and environmental effects. With lower values ​​of s_volume_dB, weapons become loud while the rest normally decreases in volume, I can't increase the volume of the speakers too much to hear the audio logs, because otherwise the shots of the weapons would make me become deaf. I should continually use speaker knob.

For me it is to be considered as a bug, I don't know if the developers meant that all this worked like this, but unless they were drunk, I don't think.

If it is not possible to do anything or it is too complex, I don't ask you to solve this problem, I would say that you have done too much to solve all the unsolved bugs of this game.

The limiter has solved this bug if you play with EAX disabled (but the game, in this case, is perfectly playable with s_volume_dB "0", I don't know any audible clipping, despite your tests affirm the opposite).
As already mentioned, I'm not an audio expert, but perhaps in this case the clipping is negligible, as the speakers don't distort the sound. Maybe it could happen in recent games as well. Perhaps the DAC or the amplifier have a "endurance threshold", I don't know...

I don't know if even these "inaudible" clippings can damage the speakers, I don't know if the Windows master volume should be set below 100%... Unfortunately there are too many different and conflicting opinions on the web, so I gave up and decided listen with my ears.

**Comment by bibendovsky** [comment]
I will keep the limiter only for "software" sound subsystem.
Current tests with OpenAL subsystem shows problems which I don't know how to resolve for now.

**Pull request merged**
